version: "3.8"

services:
  novadraw_server:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: novadraw_server
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./backend/storage:/app/storage
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

volumes:
