name: nova_draw_ai
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  go_router: ^16.3.0
  cupertino_icons: ^1.0.8
  easy_localization: ^3.0.8
  intl: ^0.20.2
  provider: ^6.1.5+1
  http: ^1.5.0
  image_picker: ^1.2.0
  flutter_tts: ^4.2.3
  record: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/translations/
